variables:
  WORK: "/tmp"
  LMOD_REDIRECT: "yes"
  XML_FILE: "crane_modules.xml"
  MODULES_DIR: "/util/opt/modulefiles"

stages:
  - test
  - updatexml
  - deploy

test-modules:
  stage: test
  image: unlhcc/crane-build-el6
  except:
    - master
  tags:
    - docker
  before_script:
    - ln -s $CI_PROJECT_DIR $MODULES_DIR
    - source /util/opt/lmod/lmod/init/profile
  script:
    - module av > /dev/null
    - module spider > /dev/null

test-paths:
  stage: test
  image: unlhcc/crane-build-el6
  except:
    - master
  tags:
    - crane-test
  script:
    - scripts/test_changed_modules.sh

updatexml:
  stage: updatexml
  image: unlhcc/crane-build-el6
  allow_failure: yes
  only:
    - master
  tags:
    - docker
  before_script:
    - ln -s $CI_PROJECT_DIR $MODULES_DIR
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
    - git config user.name "HCC Gitlab CI"
    - git config user.email "hcc-support@unl.edu"
    - git remote add origin-push git@git.unl.edu:${CI_PROJECT_PATH}.git
    - git checkout $CI_COMMIT_REF_NAME
  script:
    - /util/opt/lmod/lmod/libexec/spider -o xmlSoftwarePage $MODULES_DIR/Core > $XML_FILE
    - git add $XML_FILE    
    - git commit -m "Automated XML update [skip ci]"
    - git push origin-push $CI_COMMIT_REF_NAME || true

deploy:
  stage: deploy
  environment:
    name: crane_production
    url: https://crane.unl.edu
  image: unlhcc/crane-build-el6
  only:
    - master
  tags:
    - crane
  before_script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
  script:
    - cd $MODULES_DIR
    - git checkout master
    - git fetch
    - git checkout $CI_COMMIT_SHA
