help(
[[
The TransDecoder module file defines the following environment variables:
PATH for the location of the TransDecoder executables.

Version 2.0.1
]]
)

whatis("Name: TransDecoder")
whatis("Version: 2.0.1")
whatis("Category: computational biology, genomics")
whatis("Keywords: Biology, Genomics, Assembly, RNAseq, Transcriptome Profiling")
whatis("URL: https://transdecoder.github.io")
whatis("Description: TransDecoder identifies candidate coding regions within transcript sequences, such as those generated by de novo RNA-Seq transcript assembly using Trinity, or constructed based on RNA-Seq alignments to the genome using Tophat and Cufflinks.")

prepend_path("PATH",		"/util/opt/transdecoder/2.0/gcc/4.4")
prepend_path("PATH",		"/util/opt/transdecoder/2.0/gcc/4.4/util/bin")
prepend_path("PATH",		"/util/opt/transdecoder/2.0/gcc/4.4/util")
